apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rudzm/argo-rollouts-gitops-kind-demo.git
    targetRevision: HEAD
    path: argocd-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
